name: MPS compatibility

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  # allow manual execution just in case
  workflow_dispatch:

jobs:
  build-mps-components:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        version:
# Testing with the first and last version of the supported range should be enough. Breaking changes usually stay there
# after being introduced. It's not expected that an incompatibility only exists in some intermediate version and then
# becomes compatible again.
#          - "2020.3.6" VersionFixer was replaced by ModuleDependencyVersions in 2021.1 (used by model-sync-plugin)
          - "2021.1"
          - "2021.2"
          - "2021.3"
          - "2022.2"
          - "2022.3"
          - "2023.2"

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with ${{ matrix.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          ./gradlew --build-cache
          build
          -Pmps.version.major=${{ matrix.version }}
      - name: Archive test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-${{ matrix.version }}
          path: |
            */build/test-results
            */build/reports
